# $FreeBSD$
	
PORTNAME=       congif
PORTVERSION=    1.0
CATEGORIES=     graphics
	
MAINTAINER=     gianni.pollina@gmail.com
COMMENT=        Converts a terminal session file into animated gif

WRKSRC=	${WRKDIR}/${PORTNAME}-1.0

USES=	tar:bzip2 gmake
	
PLIST_FILES=    bin/${PORTNAME}
	

.include <bsd.port.mk>


# $FreeBSD$
